var d=null,e="Nope;Keep Trying;Nadda;Sorry;No one's home;Arg;Bummer;Faux pas;Whoops;Snafu;Blunder".split(";");
$(".dropdown-menu a").click(function(){$("input[name=points]").c($(this).data("points")).h();"undefined"!=typeof $(this).data("name")?$("input[name=name]").c($(this).data("name")).h():$("input[name=name]").c($(this).text()).h();"Yes"==$(this).data("shared")?$("#shared_task_cb").e("checked","checked").b():$("#shared_task_cb").e("checked",d).b();var a=$(this).data("reminders");if("undefined"==typeof a)$("#reminder_cb").e("checked","checked").b();else{$("#reminder_cb").e("checked",d).b();$("#reminder-details #rem_reminder:visible").click();
for(var b=0;b<a.length;b++){var c=a[b][0],f=a[b][1],i="#reminder-details .controls:nth("+b+")";0==$(i).length&&($("#reminder-details .controls:last #add_reminder").click(),$(i));$(i+" input").c(c);$(i+" select option:nth("+f+")").e("selected","selected")}}$(".dropdown.open .dropdown-toggle").t("toggle")});$(".tt-right").I({j:"right"});$(".pop-below").m({j:"bottom",n:"hover",k:{show:200,f:300}});$(".pop-right").m({j:"right",n:"hover",k:{show:200,f:0}});
function g(a,b){if(!0==b)var c="error",f="success";else c="success",f="error";$(a).a(c).d(f);$(a).l(".control-group").a(c).d(f)}
$("#when").bind("keyup",function(){p=Date.parse($("#when").c());$("#date-info").remove();p==d?($('<span id="date-info" class="inline-help"> <i class="icon-exclamation-sign"></i> '+e[Math.round(e.length*Math.random())]+"...</span>").g($("#when").parent()),setTimeout(g,5,$("#when"),!1)):$('<span id="date-info" class="inline-help"> <i class="icon-ok"></i> '+p.toString("dddd dd MMMM, yyyy")+"</span>").g($("#when").parent())});
$("#when").i("blur",function(){var a=$("#date-info");a!=d&&(a.children("i").A("icon-ok")?($("#when").c($.trim(a.text())),$("#when").a("error").d("success"),setTimeout(g,5,$("#when"),!0),a.remove()):setTimeout(g,5,$("#when"),!1))});$("#cal-icon").e("data-date",Date.H().toString("dd/MM/yyyy"));$("#cal-icon").s().D("changeDate",function(a){$("#when").c(a.r.toString("dddd dd MMMM, yyyy"));$("#date-info").remove();setTimeout(g,5,$("#when"),!0);$(".datepicker").f()});
function h(a){return"undefined"!=$(a).e("checked")&&"checked"==$(a).e("checked")}$("#repeat-times").b(function(){h($("#repeat-times-check"))?$("#repeat-times-input").d("required").d("number").parent().parent().parent().a("error").a("success"):$("#repeat-times-input").a("required").a("error").c("").parent().parent().parent().a("error").a("success").find(".inline-help").remove()});
$("#shared-num").b(function(){h($("#shared-num-check"))?$("#shared-num-input").d("required").d("number").parent().parent().parent().a("error").a("success"):$("#shared-num-input").a("required").a("error").c("").parent().parent().parent().a("error").a("success").find(".inline-help").remove()});$("#repeats_cb").b(function(){h(this)?$("#repeat-options").show():$("#repeat-options").f()});
$("select[name=repeat_period]").b(function(){$("#freq-desc").parent().parent().show();$("#weekdays").f();$("#monthday").f();switch($(this).c()){case "Daily":$("#freq-desc").text("days");break;case "Weekly":$("#freq-desc").text("weeks");$("#weekdays").show();break;case "Monthly":$("#freq-desc").text("months");$("#monthday").show();break;case "Yearly":$("#freq-desc").parent().parent().f()}});$("#shared_task_cb").b(function(){h(this)?$("#shared-options").show():$("#shared-options").f()});$("select[name=repeat_period]").c("Daily").b();
$("#repeats_cb").e("checked",d).b();$("#shared_task_cb").e("checked",d).b();$("#rem_reminder").f();$("#add_reminder").click(function(){if(9<$("div[id=reminder-options]").length)alert("Sorry, there is a maximum of 10 reminders allowed.");else{var a=$("#reminder-details > div :first").p().g("#reminder-details > div :last");$(a).children(".control-label").remove();$(a).find("#add_reminder").remove();$(a).find("#rem_reminder").show()}});$("#rem_reminder").i("click",function(){$(this).parent().parent().remove()});
$("#reminder_cb").b(function(){h(this)?$("#reminder-details").f():$("#reminder-details").show()});
$(".time").i("keyup",function(){var a=$.trim($(this).c()),b=/^[0-1]?[0-9]((:|.)[0-5][0-9])?[\s]*(am|pm)$/i.test(a)||/^([0-1][0-9]|2[0-4])(:|.)([0-5][0-9])$/.test(a);$(this).parent().find("#time-info").remove();b?setTimeout(g,5,$(this),!0):(""!=a&&$('<span id="time-info" class="inline-help"> <i class="icon-exclamation-sign"></i> '+e[Math.round(e.length*Math.random())]+"...</span>").g($(this).parent().children().C()),setTimeout(g,5,$(this),!1))});$(".time").blur(function(){$(this).h()});
$("form").K({u:"span",J:"success",v:function(a,b){var c=$(b).l(".control-group").a("success").d("error");$(a).o(c.children(".controls")).d("inline-help")},G:function(a){$(a).parent().q(".control-group").a("error").d("success");$(a).remove()},B:function(){var a=$('<div class="alert alert-error"><button type="button" class="close" data-dismiss="alert">\u00d7</button>Please correct the errors above.</div>').g($(this)).w("slow");setTimeout(function(){$(a).z("slow")},2E3)},F:function(a){post_form("/task/create",
a,$("form"))}});