application: sharehousegame
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /flux/css
  static_dir: css

- url: /flux/js
  static_dir: js

- url: /flux/img
  static_dir: img

- url: /flux/.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"
