application: sharehousegame
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /gae_mini_profiler/static
  static_dir: gae_mini_profiler/static

- url: /gae_mini_profiler/.*
  script: gae_mini_profiler/main.py

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /img
  static_dir: img

- url: /.*
  script: main.app

- url: /backend/send-reminders
  script: main.app
  login: admin

- url: /api/wipe
  script: main.app
  login: admin

- url: /stats.*
  script: google.appengine.ext.appstats.ui.app


admin_console:
 pages:
 - name: Appstats
   url: /_ah/stats
  
libraries:
- name: webapp2
  version: "2.5.1"

- name: jinja2
  version: "latest"


builtins:
- deferred: on
- remote_api: on
- appstats: on